#!/bin/bash

MODULE=learners                     # Learner Module
PACKAGE=org.learner.${MODULE}       # Package name

# Use the absolute path for the SSL root and the library
SSL_ROOT=/Users/al.halshareedah/Documents/GitHub/HVLearn/ssl                  # SSL root path

MAX_INIT_MEM=1024m
MAX_ALLOC_MEM=10g

MAIN=JNIDFACertname                 # Main class

LIBRARY=$1
ARGS="$@"

cd ${MODULE}

# Set the java.library.path to the absolute path of your native library
export MAVEN_OPTS="-Xms$MAX_INIT_MEM \
                   -Xmx$MAX_ALLOC_MEM \
                   -Djava.library.path=${SSL_ROOT}/${LIBRARY}"

# Maven execute
mvn -q -e exec:java -Dexec.mainClass="$PACKAGE.$MAIN" -Dexec.args="${ARGS}"

cd -
